/**
 * Created by J-moneyham on 10/26/16.
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem2 {
    public static void main(String[] args) {

        int a = 0;
        int b = 1;
        int sumEvens = 0;

        while (a < 4000000 && b < 4000000) {
            int fibi = a + b;
            System.out.println(fibi);
            if (fibi >= 4000000) break;
            a = b;
            b = fibi;

            if (fibi % 2 == 0) {
                sumEvens += fibi;
            }
        }

        System.out.println("Answer: " + sumEvens);
    }
}
